### ISSUE TITLE
missing const_tag2idx.json

### ISSUE THREAD

**Issue by sairin1202** [adymaharana/VLCStoryGan#1]
Hi, very nice work. Thank you for sharing your code.
When I run the code, it reports an error that const_tag2idx.json is missing.
How can I get this file?
Thank you

**Comment by sairin1202** [comment]
Hi, thanks for your response. When can we have the updated data for training? or could you provide your pretrained model.
Thanks a lot

**Comment by htthYjh** [comment]
Preparing TRAINING dataset
Total number of clips 10191
Traceback (most recent call last):
  File "/hy-tmp/VLCStoryGan/train_vlcgan.py", line 103, in <module>
    storydataset = data.StoryDataset(base, dir_path, video_transforms, cfg.MARTT.num_hidden_layers,
  File "/hy-tmp/VLCStoryGan/vlcgan/pororo_data_const.py", line 213, in __init__
    self.const_tag2id = json.load(open(textvec + 'const_tag2idx.json'))
FileNotFoundError: [Errno 2] No such file or directory: './data/data/const_tag2idx.json'

when i run with train_vlcgan.py , file of const_tag2idx.json is missing.

**Comment by KyonP** [comment]
Is the file `const_tag2idx.json` uploaded?  I couldn't find it 😢

**Comment by KyonP** [comment]
> 

I found it from the Pororo dataset link attached on Readme. 😄
